name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - run: ./tools/make.sh --test
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: test-binaries
          path: build/unittest/fmtreader_test
