name: Build and test
on: [push]
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./tools/make.sh --test
      - run: mkdir -p test-results
      - run: ./build/unittest/fmtreader_test --gtest_output=xml:test-results/test-linux.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/*.xml
