name: Publish test results
on:
  workflow_run:
    workflows: ["Unit Testing"]
    types:
      - completed
jobs:
  publish_test_results:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          name: test-results
          path: test_results
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Unit Tests
          path: test_results/*.xml
          reporter: java-junit
