name: Unit Testing
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v2
        with:
          name: test-binaries
      - run: mkdir -p test-results
      - run: ./test-binaries/fmtreader_test --gtest_output=xml:test-results/test-linux.xml
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: test-binaries
          path: test-results/*.xml

