name: Unit Testing
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: test-binaries
          path: test_binaries
      - run: mkdir -p test-results
      - run: chmod +x ./test_binaries/fmtreader_test
      - run: ./test_binaries/fmtreader_test --gtest_output=xml:test-results/test-linux.xml
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: test-results
          path: test-results/*.xml
